version: '3.6'
    
services: 
    # MySQL
    db:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"     
        volumes: 
            - ./init:/docker-entrypoint-initdb.d